language: java
jdk:
- oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - oracle-java8-installer
deploy:
  provider: releases
  file:
  - "./PathfinderAPI/target/PathfinderAPI.jar"
  - "./PathfinderAPI/target/PathfinderAPI-sources.jar"
  skip_cleanup: true
  on:
    tags: true
    repo: ysl3000/PathfindergoalAPI
  overwrite: true
  api_key:
    secure: VzyX+oKeVs2lJ/jKheEdsMC2PQF/FYAgLgWmSqPxJ2pD5vgDqvCAHjHtD6T3JGzlL5r5twc8qbPe41LktLJ4ex9KlII2ms4oLTdheJtORmxy/ec/Fz2Craht6c94v4B6TDwdnqFBmgk6lS//2b5UWi8itEljLsL7dbCUVhingRizV39Yiq8VruKq8z0yeUAh9wpKMHRMohZv09oWJOBwQ6vNymhbTTu0BczQl1dTY4v6Mh75fH3ewVDnjbzmaMO/1LlqI/PDWlabNXmX+3NN9XrllD2vaJmp8IGsMHC9zlwNdem38j3IM6DlHI2Kx0Wg2aXU+q3MhXJZ/j/stygBtfULNlXaT525KiG5UXmnWaL+cqwsdIgsY7BGDnXz0pK3sxBd0dcmVXIYCTWMxdzDOSlJCHMF4JmqVLNs4Y5zZi0787CGweHFpC0OXF6A+RizLY0CuexfuLTk83UB5J6/FmHbmjOjAzQFmFPHTVNo8Ef/P5Nzo763tsEbdnz8OOdYmBvvHSBd1mL6g5941FY7Zte0bo00cZfjn5fx4VE0w5lOqpt2QjJ0Xcx5v0BwI7AzIgtw3/CKK7DGNmGhDnz76FmuH68PbTOx0obJYd6gdGHIyVxU83PeZWZ83GcZ8tCv93yWhooWPaFvvJVd5hicsmPv4ee/ria+WDKlliW/FDU=
env:
  - ci=true
script:
  - mvn -pl "!PathfinderAPI" clean install